export const todos =[
    {
        'id': '1',
        'titre': 'Test1',
        'description': 'LOREM IPSUM1',
        'dueDate': '10/11/2021',
        'statut': false,
        'labelId': '1',
        'creationDate': '03/11/2021',
    },
    {
        'id': '2',
        'titre': 'Test2',
        'description': 'LOREM IPSUM2',
        'dueDate': '10/11/2021',
        'statut': true,
        'labelId': '1',
        'creationDate': '03/11/2021',
    },
    {
        'id': '3',
        'titre': 'Test3',
        'description': 'LOREM IPSUM3',
        'dueDate': '10/11/2021',
        'statut': true,
        'labelId': '1',
        'creationDate': '03/11/2021',
    },
    {
        'id': '4',
        'titre': 'Test4',
        'description': 'LOREM IPSUM4',
        'dueDate': '10/11/2021',
        'statut': false,
        'labelId': '1',
        'creationDate': '03/11/2021',
    },
    {
        'id': '5',
        'titre': 'Test5',
        'description': 'LOREM IPSUM5',
        'dueDate': '10/11/2021',
        'statut': true,
        'labelId': '1',
        'creationDate': '03/11/2021',
    },
    ]